// Markdown for Agents — edge content negotiation for a Cloudflare Worker that
// serves static assets.
//
// This site is deployed as a Worker (Workers Static Assets), NOT Cloudflare
// Pages, so the old Pages convention (functions/_middleware.js) is ignored by
// the runtime. This Worker replaces it. wrangler.jsonc sets
// `assets.run_worker_first: true`, so this fetch handler runs on every request
// and serves the static asset itself via the ASSETS binding (env.ASSETS.fetch),
// which still applies public/_headers and public/_redirects.
//
// When a client expresses `Accept: text/markdown`, serve the prebuilt Markdown
// representation of the page (generated by scripts/sync-docs.mjs into public/)
// instead of HTML. Browsers send `Accept: text/html,...` (no text/markdown), so
// they keep getting HTML — this only changes the response for agents/LLMs that
// ask for Markdown.
//
// Response carries `Content-Type: text/markdown; charset=utf-8`,
// `x-markdown-tokens` (estimated token count), and `Vary: Accept` so caches keep
// the HTML and Markdown variants separate.

// Rough token estimate (~4 chars/token), matching the heuristic Cloudflare's
// native Markdown for Agents uses for its x-markdown-tokens header.
const estimateTokens = (text) => Math.max(1, Math.ceil(text.length / 4));

// True when the client actually prefers Markdown. Browsers never include
// text/markdown in Accept, so a presence check is sufficient and safe.
const wantsMarkdown = (accept) => /(^|[,\s])text\/markdown\b/i.test(accept || '');

// A "page" is an extensionless route (/, /faq/, /reference/design/). Requests
// for real files (.css, .js, .md, .png, …) are passed straight through.
const isPageRequest = (pathname) => !/\.[^/]+$/.test(pathname.replace(/\/+$/, ''));

// Map a page route to its prebuilt Markdown asset:
//   /                  -> /index.md
//   /faq/              -> /faq.md
//   /reference/design/ -> /reference/design.md
const markdownAssetPath = (pathname) => {
  const p = pathname.replace(/\/+$/, '');
  return (p === '' ? '/index' : p) + '.md';
};

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    const negotiable =
      (request.method === 'GET' || request.method === 'HEAD') &&
      isPageRequest(url.pathname);

    if (negotiable && wantsMarkdown(request.headers.get('Accept'))) {
      // Fetch the prebuilt Markdown asset. The `.md` path has an extension, so
      // serving it can't recurse back into negotiation.
      const mdUrl = new URL(markdownAssetPath(url.pathname), url.origin);
      const mdResp = await env.ASSETS.fetch(
        new Request(mdUrl, { method: 'GET', headers: { Accept: 'text/plain' } })
      );

      if (mdResp.status === 200) {
        const body = await mdResp.text();
        return new Response(request.method === 'HEAD' ? null : body, {
          status: 200,
          headers: {
            'Content-Type': 'text/markdown; charset=utf-8',
            'x-markdown-tokens': String(estimateTokens(body)),
            'Vary': 'Accept',
            'Cache-Control': 'public, max-age=3600',
          },
        });
      }
      // No Markdown variant for this route — fall through to the HTML response.
    }

    const response = await env.ASSETS.fetch(request);

    // Tell caches the representation depends on Accept for negotiable pages.
    if (negotiable) {
      const r = new Response(response.body, response);
      const vary = r.headers.get('Vary');
      r.headers.set(
        'Vary',
        vary && !/\baccept\b/i.test(vary) ? `${vary}, Accept` : vary || 'Accept'
      );
      return r;
    }
    return response;
  },
};
